version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "${QDRANT_HTTP_PORT:-6333}:6333"
    volumes:
      - ./data/qdrant:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ./models/ollama:/root/.ollama

  api:
    build:
      context: ./api
    image: warframe-api:local        # local image built by Portainer
    container_name: warframe-rag-api
    restart: unless-stopped
    depends_on: [qdrant, ollama]
    environment:
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_URL=http://ollama:11434
      - RAG_API_PORT=${RAG_API_PORT:-8088}
      - TOP_K=${TOP_K:-8}
      - CHUNK_SIZE=${CHUNK_SIZE:-900}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP:-150}
      - EMBED_MODEL=${EMBED_MODEL:-BAAI/bge-small-en-v1.5}
      - GEN_MODEL=${GEN_MODEL:-llama3.1:8b-instruct-q4_K_M}
      - COLLECTION=${COLLECTION:-warframe}
    ports:
      - "${RAG_API_PORT:-8088}:8088"

  ingestor:
    build:
      context: ./api                 # reuse the same code+deps image
    image: warframe-api:local
    container_name: warframe-ingestor
    depends_on: [qdrant]
    environment:
      - QDRANT_URL=http://qdrant:6333
      - EMBED_MODEL=${EMBED_MODEL:-BAAI/bge-small-en-v1.5}
      - CHUNK_SIZE=${CHUNK_SIZE:-900}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP:-150}
      - COLLECTION=${COLLECTION:-warframe}
    volumes:
      - ./ingest:/ingest:ro
      - ./rules.yaml:/rules.yaml:ro
    # override the default CMD to run ingestion
    command: ["python", "/app/app.py", "--ingest", "/ingest/sources.yaml", "--rules", "/rules.yaml"]
    restart: "no"
