version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "${QDRANT_HTTP_PORT:-6333}:6333"
    volumes:
      - ./data/qdrant:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ./models/ollama:/root/.ollama

  # Build the API image once; no bind mounts to /app
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: warframe-api:latest
    container_name: warframe-rag-api
    restart: unless-stopped
    depends_on: [qdrant, ollama]
    environment:
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_URL=http://ollama:11434
      - RAG_API_PORT=${RAG_API_PORT:-8088}
      - TOP_K=${TOP_K:-8}
      - CHUNK_SIZE=${CHUNK_SIZE:-900}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP:-150}
      - EMBED_MODEL=${EMBED_MODEL:-BAAI/bge-small-en-v1.5}
      - GEN_MODEL=${GEN_MODEL:-llama3.1:8b-instruct-q4_K_M}
      - COLLECTION=${COLLECTION:-warframe}
    ports:
      - "${RAG_API_PORT:-8088}:${RAG_API_PORT:-8088}"

  # Ingestor reuses the same built image; only mount data inputs
  ingestor:
    image: warframe-api:latest
    container_name: warframe-ingestor
    depends_on: [qdrant]
    environment:
      - QDRANT_URL=http://qdrant:6333
      - EMBED_MODEL=${EMBED_MODEL:-BAAI/bge-small-en-v1.5}
      - CHUNK_SIZE=${CHUNK_SIZE:-900}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP:-150}
      - COLLECTION=${COLLECTION:-warframe}
    volumes:
      - ./ingest:/ingest:ro
      - ./rules.yaml:/rules.yaml:ro
    command: >
      bash -lc "python /app/app.py --ingest /ingest/sources.yaml --rules /rules.yaml"
    restart: "no"
