version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "${QDRANT_HTTP_PORT:-6333}:6333"
    volumes:
      - ./data/qdrant:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ./models/ollama:/root/.ollama

  api:
    image: python:3.11-slim
    container_name: warframe-rag-api
    restart: unless-stopped
    depends_on: [qdrant, ollama]
    working_dir: /api
    environment:
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_URL=http://ollama:11434
      - RAG_API_PORT=${RAG_API_PORT:-8088}
      - TOP_K=${TOP_K:-8}
      - CHUNK_SIZE=${CHUNK_SIZE:-900}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP:-150}
      - EMBED_MODEL=${EMBED_MODEL:-BAAI/bge-small-en-v1.5}
      - GEN_MODEL=${GEN_MODEL:-llama3.1:8b-instruct-q4_K_M}
      - COLLECTION=${COLLECTION:-warframe}
    volumes:
      - ./api:/api
    command: >
      bash -lc "pip install --no-cache-dir -r /api/requirements.txt &&
                python -m uvicorn app:app --host 0.0.0.0 --port ${RAG_API_PORT:-8088}"
    ports:
      - "${RAG_API_PORT:-8088}:${RAG_API_PORT:-8088}"

  ingestor:
    image: python:3.11-slim
    container_name: warframe-ingestor
    depends_on: [qdrant]
    working_dir: /api
    environment:
      - QDRANT_URL=http://qdrant:6333
      - EMBED_MODEL=${EMBED_MODEL:-BAAI/bge-small-en-v1.5}
      - CHUNK_SIZE=${CHUNK_SIZE:-900}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP:-150}
      - COLLECTION=${COLLECTION:-warframe}
    volumes:
      - ./api:/api
      - ./ingest:/ingest
      - ./rules.yaml:/rules.yaml:ro
    command: >
      bash -lc "pip install --no-cache-dir -r /api/requirements.txt &&
                python /api/app.py --ingest /ingest/sources.yaml --rules /rules.yaml"
    restart: "no"
