version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "${QDRANT_HTTP_PORT:-6333}:6333"
    volumes:
      - ./data/qdrant:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ./models/ollama:/root/.ollama

  api:
    image: python:3.11-slim
    container_name: warframe-rag-api
    restart: unless-stopped
    depends_on: [qdrant, ollama]
    working_dir: /app
    environment:
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_URL=http://ollama:11434
      - RAG_API_PORT=${RAG_API_PORT:-8088}
      - TOP_K=${TOP_K:-8}
      - CHUNK_SIZE=${CHUNK_SIZE:-900}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP:-150}
      - EMBED_MODEL=${EMBED_MODEL:-BAAI/bge-small-en-v1.5}
      - GEN_MODEL=${GEN_MODEL:-llama3.1:8b-instruct-q4_K_M}
      - COLLECTION=${COLLECTION:-warframe}
    volumes:
      - ./api:/app
    command: >
      bash -lc "
        apt-get update &&
        apt-get install -y --no-install-recommends build-essential &&
        pip install --no-cache-dir -r requirements.txt &&
        python -m uvicorn app:app --host 0.0.0.0 --port ${RAG_API_PORT:-8088}
      "
    ports:
      - "${RAG_API_PORT:-8088}:${RAG_API_PORT:-8088}"

  warframe-ingestor:
    image: python:3.11-slim
    container_name: warframe-ingestor
    working_dir: /app
    volumes:
      - ./api:/app/api
      - ./ingest:/app/ingest
    command: >
      sh -c "pip install --no-cache-dir -r /app/api/requirements.txt &&
            python /app/api/app.py"


